### ISSUE TITLE
Can't Install in pubspec.yaml

### ISSUE THREAD

**Issue by zgramming** [CarnegieTechnologies/gallery_saver#22]
I get this error while installing this plugin onmy pubspec.yaml. 
```
e: C:\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\gallery_saver-1.0.4\android\src\main\kotlin\carnegietechnologies\gallery_saver\GallerySaver.kt: (65, 17): 'launch(CoroutineContext = ..., CoroutineStart = ..., suspend CoroutineScope.() -> Unit): Job' is only available since Kotlin 1.3 and cannot be used in Kotlin 1.2
e: C:\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\gallery_saver-1.0.4\android\src\main\kotlin\carnegietechnologies\gallery_saver\GallerySaver.kt: (66, 27): 'async(CoroutineContext = ..., CoroutineStart = ..., suspend CoroutineScope.() -> T): Deferred<T>' is only available since Kotlin 1.3 and cannot be used in Kotlin 1.2
e: C:\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\gallery_saver-1.0.4\android\src\main\kotlin\carnegietechnologies\gallery_saver\GallerySaver.kt: (69, 21): 'await(): T' is only available since Kotlin 1.3 and cannot be used in Kotlin 1.2
e: C:\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\gallery_saver-1.0.4\android\src\main\kotlin\carnegietechnologies\gallery_saver\GallerySaver.kt: (86, 17): 'launch(CoroutineContext = ..., CoroutineStart = ..., suspend CoroutineScope.() -> Unit): Job' is only available since Kotlin 1.3 and cannot be used in Kotlin 1.2
e: C:\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\gallery_saver-1.0.4\android\src\main\kotlin\carnegietechnologies\gallery_saver\GallerySaver.kt: (87, 27): 'async(CoroutineContext = ..., CoroutineStart = ..., suspend CoroutineScope.() -> T): Deferred<T>' is only available since Kotlin 1.3 and cannot be used in Kotlin 1.2
e: C:\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\gallery_saver-1.0.4\android\src\main\kotlin\carnegietechnologies\gallery_saver\GallerySaver.kt: (90, 21): 'await(): T' is only available since Kotlin 1.3 and cannot be used in Kotlin 1.2

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':gallery_saver:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 28s
Gradle task assembleDebug failed with exit code 1
```
I'm mistake Something ?

**Comment by vlada3003** [comment]
e: C:\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\gallery_saver-1.0.4\android\src\main\kotlin\carnegietechnologies\gallery_saver\GallerySaver.kt: (90, 21): 'await(): T' is only available since Kotlin 1.3 and cannot be used in Kotlin 1.2

Based on the above error, it looks like you are using an older version of Kotlin in your project. Can you please upgrade Kotlin's dependency to 1.3?

**Comment by zgramming** [comment]
After update Kotlin to 1.3 everything is ok.
Thank's for your response.

**Comment by vishwajit76** [comment]
what about kotlin latest stable 1.4?
